# Generated by Django 4.1 on 2024-06-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='example',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='english',
            name='meaning',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
