# Generated by Django 4.1 on 2024-07-15 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_english_example_english_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='english',
            name='genre',
            field=models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJECTIVE', 'Adjective'), ('ADVERB', 'Adverb'), ('PRONOUN', 'Pronoun'), ('PREPOSITION', 'Preposition'), ('CONJUNCTION', 'Conjunction'), ('INTERJECTION', 'Interjection')], default='NOUN', max_length=100),
        ),
        migrations.AddField(
            model_name='english',
            name='rank',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
