# Generated by Django 4.1 on 2024-07-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_english_caca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='english',
            name='caca',
        ),
    ]
