# Generated by Django 4.1 on 2024-07-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_english_caca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='example',
            name='english',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.english'),
        ),
    ]
