# Generated by Django 4.1 on 2024-07-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_english_id_alter_example_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
