# Generated by Django 4.1 on 2024-07-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_example_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='english',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='listings.english'),
            preserve_default=False,
        ),
    ]
